
stages:
  - build
  - unit-testing
  - interpretation-testing
  - run-testing

.default:
  rules:
    - if:  # $CI_PIPELINE_SOURCE == "schedule"
  script:
    - java -jar $YADL_JAR $ARG
  variables:
    YADL_PATH: target/scala-3.4.1
    YADL_JAR: $YADL_PATH/yadl.jar

default:
  cache:
    key: build-cache
    paths:
      - !reference [.default, variables, YADL_PATH]

build:
  stage: build
  script:
    - sbt clean compile # assembly
  rules:
    - !reference [.default, rules]
  timeout: 3 min

unit-tests:
  stage: unit-testing
  needs:
    - build
  script:
    - sbt test
  rules:
    - !reference [.default, rules]
  timeout: 5 min

simple-exprs:
  stage: interpretation-testing
  needs:
    - unit-tests
  script:
    - !reference [.default, script]
  variables: 
    ARG: tests/simple.yadl
    YADL_PATH: !reference [.default, variables, YADL_PATH]
    YADL_JAR: !reference [.default, variables, YADL_JAR]
  rules:
    - !reference [.default, rules]
  timeout: 3 min

function-exprs:
  stage: interpretation-testing
  needs:
    - unit-tests
  script:
    - !reference [.default, script]
  variables:
    ARG: tests/function.yadl
    YADL_PATH: !reference [.default, variables, YADL_PATH]
    YADL_JAR: !reference [.default, variables, YADL_JAR]
  rules:
    - !reference [.default, rules]
  timeout: 3 min

if-branches-exprs:
  stage: interpretation-testing
  needs:
    - unit-tests
  script:
    - !reference [.default, script]
  variables:
    ARG: tests/if-branches.yadl
    YADL_PATH: !reference [.default, variables, YADL_PATH]
    YADL_JAR: !reference [.default, variables, YADL_JAR]
  rules:
    - !reference [.default, rules]
  timeout: 3 min

while-loop-exprs:
  stage: interpretation-testing
  needs:
    - unit-tests
  script:
    - !reference [.default, script]
  variables:
    ARG: tests/whileloop.yadl
    YADL_PATH: !reference [.default, variables, YADL_PATH]
    YADL_JAR: !reference [.default, variables, YADL_JAR]
  rules:
    - !reference [.default, rules]
  timeout: 3 min

python-test-script:
  stage: run-testing
  needs:
    - simple-exprs
    - function-exprs
    - if-branches-exprs
    - while-loop-exprs
  script:
    - pytest
  rules:
    - !reference [.default, rules]
  variables: !reference [.default, variables]
  artifacts:
    paths:
      - $YADL_JAR
  timeout: 3 min

