
stages:
  - build
  - unit-testing
  - interpretation-testing

.config: &config
  rules: &default_rules
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    YADL_PATH: &path target/scala-3.4.1
    YADL_JAR: &jar $YADL_PATH/yadl.jar

default:
  cache:
    key: build-cache
    paths:
      - *path

build:
  stage: build
  script:
    - sbt clean compile assembly
  rules: *default_rules
  timeout: 3 min

unit-tests:
  stage: unit-testing
  needs:
    - build
  script:
    - sbt test
  rules: *default_rules
  timeout: 5 min

python-test-script:
  <<: *config
  stage: interpretation-testing
  needs:
    - unit-tests
  script:
    - pytest
  artifacts:
    paths:
      - *jar
  timeout: 3 min

