
stages:
  - build
  - unit-testing
  - interpretation-testing
  - run-testing

.default:
  rules:
    - if:  # $CI_PIPELINE_SOURCE == "schedule"


build:
  stage: build
  script:
    - sbt clean compile
  rules:
    - !reference [.default, rules]
  timeout: 3 min

unit-tests:
  stage: unit-testing
  needs:
    - build
  script:
    - sbt test
  rules:
    - !reference [.default, rules]
  timeout: 5 min

simple-exprs:
  stage: interpretation-testing
  needs:
    - unit-tests
  script:
    - sbt 'run tests/simple.yadl'
  rules:
    - !reference [.default, rules]
  timeout: 3 min

function-exprs:
  stage: interpretation-testing
  needs:
    - unit-tests
  script:
    - sbt 'run tests/function.yadl'
  rules:
    - !reference [.default, rules]
  timeout: 3 min

if-branches-exprs:
  stage: interpretation-testing
  needs:
    - unit-tests
  script:
    - sbt 'run tests/if-branches.yadl'
  rules:
    - !reference [.default, rules]
  timeout: 3 min

while-loop-exprs:
  stage: interpretation-testing
  needs:
    - unit-tests
  script:
    - sbt 'run tests/whileloop.yadl'
  rules:
    - !reference [.default, rules]
  timeout: 3 min

python-test-script:
  stage: run-testing
  needs:
    - simple-exprs
    - function-exprs
    - if-branches-exprs
    - while-loop-exprs
  script:
    - pytest
  rules:
    - !reference [.default, rules]
  timeout: 3 min

