
stages:
  - build
  - unit-testing
  - interpretation-testing

.config: &config
  rules: &default_rules
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    YADL_PATH: &path target/scala-3.4.1
    YADL_JAR: &jar $YADL_PATH/yadl.jar
    YADL_WIN: &win zig-out/bin/yadl-win.exe
    YADL_LINUX: &linux zig-out/bin/yadl-linux
    YADL_MAC: &mac zig-out/bin/yadl-mac


default:
  cache:
    key: build-cache-$CI_COMMIT_REF_SLUG
    paths:
      - *path
      - zig-out
      - zig-cache

## scala bulid pipeline
build:
  stage: build
  script:
    - sbt clean compile assembly
  rules: *default_rules
  timeout: 3 min

unit-tests:
  stage: unit-testing
  needs:
    - build
  script:
    - sbt test
  rules: *default_rules
  timeout: 5 min

python-test-script:
  <<: *config
  stage: interpretation-testing
  needs:
    - unit-tests
    - unit-tests-zig
  script:
    - pytest
  artifacts:
    paths:
      - *jar
      - *win
      - *linux
      - *mac
  timeout: 5 min

## zig build pipeline
build-zig:
  stage: build
  script:
    - rm -rf zig-out
    - rm -rf zig-cache
    - zig build -Dtarget=x86_64-linux
    - zig build -Dtarget=x86_64-windows
    - zig build -Dtarget=aarch64-macos
  rules: *default_rules
  timeout: 3 min

unit-tests-zig:
  stage: unit-testing
  needs:
    - build-zig
  script:
    - zig build test --summary all
  rules: *default_rules  
  timeout: 5 min

build-main:
  <<: *config
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - sbt clean compile assembly
  timeout: 3 min

build-main-zig:
  <<: *config
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - rm -rf zig-out
    - rm -rf zig-cache
    - zig build -Dtarget=x86_64-linux
    - zig build -Dtarget=x86_64-windows
    - zig build -Dtarget=aarch64-macos
  timeout: 3 min

python-script-main:
  <<: *config
  stage: interpretation-testing
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  needs:
    - build-main
    - build-main-zig
  script:
    - pytest
  artifacts:
    paths:
      - *jar
      - *win
      - *linux
      - *mac
  timeout: 5 min


