
name: CI (scala version) 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  YADL_JAR: target/scala-3.4.1/yadl.jar

jobs:
  build:
    name: Build step
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Setting up python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Installing pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Building source
      run: sbt assembly
    - name: Run tests
      run: sbt test
    - name: Running pytest
      continue-on-error: true
      run: pytest test-scripts/scala/
      
      
