
name: Zig CI Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  YADL_WIN: zig-out/bin/yadl-win

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest ziglang
    - name: Zig build
      run: python -m ziglang build
    - name: parser.zig unit tests
      run: python -m ziglang test src/zig/parser.zig
    - name: Runnning pytest
      run: python -m pytest test-scripts/zig/*
 
