
name: Zig CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  YADL_BIN: zig-out/bin/yadl-linux

jobs:
  build:
    name: Zig Build on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest ziglang
    - name: Zig build
      run: python -m ziglang build
    - name: Zig unit tests
      run: python -m ziglang build test --summary all
    - name: pytest step
      run: python -m pytest test-scripts/*
 
